services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: servigic
    ports:
      - "5432:5432"
    volumes:
      - servigic_pgdata:/var/lib/postgresql/data

volumes:
  servigic_pgdata:
